default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password
  host: db
  port: 3306

development:
  <<: *default
  database: freemarket_app_development

test:
  <<: *default
  database: freemarket_app_test

production:
  <<: *default
  database: freemarket_app_production